// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB67yuxKe2p6b2iEFHLMhg8SZqh7NqnM_c',
    appId: '1:915715018956:web:7c829b23e39a174f9af269',
    messagingSenderId: '915715018956',
    projectId: 'bmicalculator-v2',
    authDomain: 'bmicalculator-v2.firebaseapp.com',
    storageBucket: 'bmicalculator-v2.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCsKXcKY82RK2AyKOAjq3RE-6fpN7TP7cs',
    appId: '1:915715018956:android:72473844c814bb509af269',
    messagingSenderId: '915715018956',
    projectId: 'bmicalculator-v2',
    storageBucket: 'bmicalculator-v2.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB67yuxKe2p6b2iEFHLMhg8SZqh7NqnM_c',
    appId: '1:915715018956:web:38482874c198c6829af269',
    messagingSenderId: '915715018956',
    projectId: 'bmicalculator-v2',
    authDomain: 'bmicalculator-v2.firebaseapp.com',
    storageBucket: 'bmicalculator-v2.firebasestorage.app',
  );
}
