// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAFPC_C6BJ4x8ecVnsS7_hwLDsMhcfXys8',
    appId: '1:984799919369:web:ee45b2bfae83e4c8b8a7d8',
    messagingSenderId: '984799919369',
    projectId: 'bmicalculator-2ec34',
    authDomain: 'bmicalculator-2ec34.firebaseapp.com',
    storageBucket: 'bmicalculator-2ec34.firebasestorage.app',
    measurementId: 'G-QXTXFD73Z7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7mAfyJEZ0NUJw2Ow_ATYg1-J0ZKsmS7M',
    appId: '1:984799919369:android:636aa823a22d3b67b8a7d8',
    messagingSenderId: '984799919369',
    projectId: 'bmicalculator-2ec34',
    storageBucket: 'bmicalculator-2ec34.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAFPC_C6BJ4x8ecVnsS7_hwLDsMhcfXys8',
    appId: '1:984799919369:web:cbf4c4d1513bc7c0b8a7d8',
    messagingSenderId: '984799919369',
    projectId: 'bmicalculator-2ec34',
    authDomain: 'bmicalculator-2ec34.firebaseapp.com',
    storageBucket: 'bmicalculator-2ec34.firebasestorage.app',
    measurementId: 'G-W1DXWWFEFZ',
  );
}
